/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billing_system;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

/**
 *
 * @author junie
 */
public class BillingInterface extends javax.swing.JFrame {
    private String totalCost;
    private String tax;
    private String subTotal;
    private double[] cost = new double[20];
    private List<Menu> productPurchased = new ArrayList<>(10);

    /**
     * Creates new form BillingInterface
     */
    public BillingInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        totalScreen = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lastNameTxt = new javax.swing.JTextField();
        costumerRefTxt = new javax.swing.JTextField();
        firstNameTxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        product1 = new javax.swing.JCheckBox();
        product2 = new javax.swing.JCheckBox();
        product3 = new javax.swing.JCheckBox();
        product4 = new javax.swing.JCheckBox();
        product5 = new javax.swing.JCheckBox();
        product6 = new javax.swing.JCheckBox();
        product7 = new javax.swing.JCheckBox();
        product8 = new javax.swing.JCheckBox();
        product9 = new javax.swing.JCheckBox();
        product10 = new javax.swing.JCheckBox();
        price10 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        p4 = new javax.swing.JTextField();
        p5 = new javax.swing.JTextField();
        p6 = new javax.swing.JTextField();
        p7 = new javax.swing.JTextField();
        p8 = new javax.swing.JTextField();
        p9 = new javax.swing.JTextField();
        p10 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        p1 = new javax.swing.JTextField();
        price2 = new javax.swing.JTextField();
        price3 = new javax.swing.JTextField();
        price4 = new javax.swing.JTextField();
        price5 = new javax.swing.JTextField();
        price6 = new javax.swing.JTextField();
        price7 = new javax.swing.JTextField();
        price8 = new javax.swing.JTextField();
        price9 = new javax.swing.JTextField();
        price1 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        exitBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Billing System");
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\junie\\Documents\\NetBeansProjects\\Billing_System\\src\\image\\financial-4560047_640.jpg"));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 51, 51)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 51, 51)));

        totalScreen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalScreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(totalScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 760, 130));

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("LAST NAME:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("COSTUMER_REF:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("FIRST NAME:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 30));

        lastNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTxtActionPerformed(evt);
            }
        });
        jPanel4.add(lastNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 140, 30));

        costumerRefTxt.setEnabled(false);
        jPanel4.add(costumerRefTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 140, 30));

        firstNameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstNameTxtMouseClicked(evt);
            }
        });
        firstNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTxtActionPerformed(evt);
            }
        });
        jPanel4.add(firstNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 140, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 360, 260));

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        product1.setText("Kimchi");
        product1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product1ActionPerformed(evt);
            }
        });
        jPanel5.add(product1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, -1));

        product2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        product2.setText("Ice Cream");
        product2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product2ActionPerformed(evt);
            }
        });
        jPanel5.add(product2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        product3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        product3.setText("Halo halo");
        product3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product3ActionPerformed(evt);
            }
        });
        jPanel5.add(product3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, -1));

        product4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        product4.setText("Soup");
        product4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product4ActionPerformed(evt);
            }
        });
        jPanel5.add(product4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, -1));

        product5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        product5.setText("MilkTea");
        product5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product5ActionPerformed(evt);
            }
        });
        jPanel5.add(product5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, -1));

        product6.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        product6.setText("Magic Sarap");
        product6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product6ActionPerformed(evt);
            }
        });
        jPanel5.add(product6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, -1));

        product7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        product7.setText("Aji ginisa");
        product7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product7ActionPerformed(evt);
            }
        });
        jPanel5.add(product7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, -1));

        product8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        product8.setText("Bechin");
        product8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product8ActionPerformed(evt);
            }
        });
        jPanel5.add(product8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 70, -1));

        product9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        product9.setText("Paminta");
        product9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product9ActionPerformed(evt);
            }
        });
        jPanel5.add(product9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 80, -1));

        product10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        product10.setText("Eden");
        product10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product10ActionPerformed(evt);
            }
        });
        jPanel5.add(product10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 70, -1));

        price10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price10.setText("100");
        price10.setEnabled(false);
        price10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price10ActionPerformed(evt);
            }
        });
        jPanel5.add(price10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 70, -1));

        p2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2.setText("0");
        p2.setEnabled(false);
        jPanel5.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 70, -1));

        p3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p3.setText("0");
        p3.setEnabled(false);
        jPanel5.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 70, -1));

        p4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p4.setText("0");
        p4.setEnabled(false);
        jPanel5.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 70, -1));

        p5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p5.setText("0");
        p5.setEnabled(false);
        jPanel5.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 70, -1));

        p6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p6.setText("0");
        p6.setEnabled(false);
        jPanel5.add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 70, -1));

        p7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p7.setText("0");
        p7.setEnabled(false);
        jPanel5.add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 70, -1));

        p8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p8.setText("0");
        p8.setEnabled(false);
        jPanel5.add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 70, -1));

        p9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p9.setText("0");
        p9.setEnabled(false);
        jPanel5.add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 70, -1));

        p10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p10.setText("0");
        p10.setEnabled(false);
        jPanel5.add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 70, -1));

        jTextField29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField29.setText("PRICE");
        jTextField29.setEnabled(false);
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 70, -1));

        p1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p1.setText("0");
        p1.setEnabled(false);
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        jPanel5.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 70, -1));

        price2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price2.setText("100");
        price2.setEnabled(false);
        price2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price2ActionPerformed(evt);
            }
        });
        jPanel5.add(price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 70, -1));

        price3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price3.setText("100");
        price3.setEnabled(false);
        price3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price3ActionPerformed(evt);
            }
        });
        jPanel5.add(price3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, -1));

        price4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price4.setText("100");
        price4.setEnabled(false);
        price4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price4ActionPerformed(evt);
            }
        });
        jPanel5.add(price4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 70, -1));

        price5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price5.setText("100");
        price5.setEnabled(false);
        price5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price5ActionPerformed(evt);
            }
        });
        jPanel5.add(price5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 70, -1));

        price6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price6.setText("100");
        price6.setEnabled(false);
        price6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price6ActionPerformed(evt);
            }
        });
        jPanel5.add(price6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 70, -1));

        price7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price7.setText("100");
        price7.setEnabled(false);
        price7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price7ActionPerformed(evt);
            }
        });
        jPanel5.add(price7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 70, -1));

        price8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price8.setText("100");
        price8.setEnabled(false);
        price8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price8ActionPerformed(evt);
            }
        });
        jPanel5.add(price8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 70, -1));

        price9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price9.setText("100");
        price9.setEnabled(false);
        price9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price9ActionPerformed(evt);
            }
        });
        jPanel5.add(price9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 70, -1));

        price1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price1.setText("100");
        price1.setEnabled(false);
        price1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price1ActionPerformed(evt);
            }
        });
        jPanel5.add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 70, -1));

        jTextField30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField30.setText("QUANTITY");
        jTextField30.setEnabled(false);
        jTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField30ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 70, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 360, 420));

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("TOTAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 12, 143, 78));

        resetBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        resetBtn.setText("RESET");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel6.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 12, 143, 78));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 360, 100));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 610));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 510));

        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 150, 60));

        printBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printBtn.setText("PRINT");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        jPanel1.add(printBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 150, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 370, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTxtActionPerformed
         Double reference = new Double(932785 + Math.random()*5678);
         Integer ref = reference.intValue();
         String costumerRef = ref.toString();
         costumerRefTxt.setText(costumerRef);
    }//GEN-LAST:event_firstNameTxtActionPerformed

    private void lastNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTxtActionPerformed

    private void price10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price10ActionPerformed

    private void product10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product10ActionPerformed
        if(product10.isSelected()){
            p10.setEnabled(true);
            p10.setText("1");
            p10.requestFocus();
            this.productPurchased.add(new Menu(9,product10.getText().toString(),100,p10.getText().toString()));
        }
        else{
            p10.setEnabled(false);
            p10.setText("0");
        }
    }//GEN-LAST:event_product10ActionPerformed

    private void product9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product9ActionPerformed
        if(product9.isSelected()){
            p9.setEnabled(true);
            p9.setText("1");
            p9.requestFocus();
            this.productPurchased.add(new Menu(8,product9.getText().toString(),100,p9.getText().toString()));
        }
        else{
            p9.setEnabled(false);
            p9.setText("0");
        }
    }//GEN-LAST:event_product9ActionPerformed

    private void product7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product7ActionPerformed
        if(product7.isSelected()){
            p7.setEnabled(true);
            p7.setText("1");
            p7.requestFocus();
            this.productPurchased.add(new Menu(6,product7.getText().toString(),100,p7.getText().toString()));
        }
        else{
            p7.setEnabled(false);
            p7.setText("0");
        }
    }//GEN-LAST:event_product7ActionPerformed

    private void product6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product6ActionPerformed
        if(product6.isSelected()){
            p6.setEnabled(true);
            p6.setText("1");
            p6.requestFocus();
            this.productPurchased.add(new Menu(5,product6.getText().toString(),100,p6.getText().toString()));
        }
        else{
            p6.setEnabled(false);
            p6.setText("0");
        }
    }//GEN-LAST:event_product6ActionPerformed

    private void product5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product5ActionPerformed
        if(product5.isSelected()){
            p5.setEnabled(true);
            p5.setText("1");
            p5.requestFocus();
            this.productPurchased.add(new Menu(4,product5.getText().toString(),100,p5.getText().toString()));
        }
        else{
            p5.setEnabled(false);
            p5.setText("0");
        }
    }//GEN-LAST:event_product5ActionPerformed

    private void product4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product4ActionPerformed
        if(product4.isSelected()){
            p4.setEnabled(true);
            p4.setText("1");
            p4.requestFocus();
            this.productPurchased.add(new Menu(3,product4.getText().toString(),100,p4.getText().toString()));
        }
        else{
            p4.setEnabled(false);
            p4.setText("0");
        }
    }//GEN-LAST:event_product4ActionPerformed

    private void product3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product3ActionPerformed
         if(product3.isSelected()){
            p3.setEnabled(true);
            p3.setText("1");
            p3.requestFocus();
            this.productPurchased.add(new Menu(2,product3.getText().toString(),100,p3.getText().toString()));
        }
        else{
            p3.setEnabled(false);
            p3.setText("0");
        }
    }//GEN-LAST:event_product3ActionPerformed

    private void product2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product2ActionPerformed
            if(product2.isSelected()){
            p2.setEnabled(true);
            p2.setText("1");
            p2.requestFocus();
            this.productPurchased.add(new Menu(1,product2.getText().toString(),100,p2.getText().toString()));
        }
        else{
            p2.setEnabled(false);
            p2.setText("0");
        }
    }//GEN-LAST:event_product2ActionPerformed

    private void product1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product1ActionPerformed
        if(product1.isSelected()){
            p1.setEnabled(true);
            p1.setText("1");
            p1.requestFocus();
            this.productPurchased.add(new Menu(0,product1.getText().toString(),100,p1.getText().toString()));
        }
        else{
            this.productPurchased.remove(0);
            p1.setEnabled(false);
            p1.setText("0");
        }
    }//GEN-LAST:event_product1ActionPerformed

    private void product8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product8ActionPerformed
                if(product8.isSelected()){
            p8.setEnabled(true);
            p8.setText("1");
            p8.requestFocus();
            this.productPurchased.add(new Menu(7,product8.getText().toString(),100,p8.getText().toString()));
        }
        else{
            p8.setEnabled(false);
            p8.setText("0");
        }
    }//GEN-LAST:event_product8ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed
    // total price
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cost[0] = Double.parseDouble(p1.getText())* Double.parseDouble(price1.getText());
        cost[1] = Double.parseDouble(p2.getText())*Double.parseDouble(price2.getText());
        cost[2] = Double.parseDouble(p3.getText())*Double.parseDouble(price3.getText());
        cost[3] = Double.parseDouble(p4.getText())*Double.parseDouble(price4.getText());
        cost[4] = Double.parseDouble(p5.getText())*Double.parseDouble(price5.getText());
        cost[5] = Double.parseDouble(p6.getText())*Double.parseDouble(price6.getText());
        cost[6] = Double.parseDouble(p7.getText())*Double.parseDouble(price7.getText());
        cost[7] = Double.parseDouble(p8.getText())*Double.parseDouble(price8.getText());
        cost[8] = Double.parseDouble(p9.getText())*Double.parseDouble(price9.getText());
        cost[9] = Double.parseDouble(p10.getText())*Double.parseDouble(price10.getText());
        
        Double sTotal = cost[0] + cost[1]+ cost[2]+ cost[3]+ cost[4]+ cost[5]+ cost[6]+ cost[7]+ cost[8]+ cost[9];
        this.subTotal = sTotal.toString();
        this.tax = "12%";
        Double totalCost = Double.parseDouble(subTotal) + 0.12;
        this.totalCost = totalCost.toString();
        
        if(!this.totalCost.equals("0.12")){
            totalScreen.setText("Sub total: P"+this.subTotal+
                " Tax: "+this.tax+"\n Total: P"
                +this.totalCost);
                String costumerReference = costumerRefTxt.getText().toString();
        String firstName = firstNameTxt.getText().toString();
        String lastName = lastNameTxt.getText().toString();
        
        Calendar dateNtime = Calendar.getInstance();
                    dateNtime.getTime();
                    SimpleDateFormat time = new SimpleDateFormat("HH:mm");
                    time.format(dateNtime.getTime());
                    SimpleDateFormat date = new SimpleDateFormat("dd:mm:yyyy");
                    date.format(dateNtime.getTime());
        jTextArea1.append("\tGabriel's mini store\n" +
            "Reference number:\t\t" +costumerReference+"\n"+
                "First name:\t\t" +firstName+"\n"+
                "Last name:\t\t" +lastName+
            "\n============================================\t " +
                "\n============================================\t ");
        for(int i = 0; i<this.productPurchased.size(); i++){
        jTextArea1.append(
            "\n"+this.productPurchased.get(i).getProductName()+":\t\t " +"x"+this.productPurchased.get(i).getQuantity()+ " Php" +cost[(int)this.productPurchased.get(i).getId()]
            );
        }
        jTextArea1.append(
            "\nSubTotal:\t\t " +"Php"+this.subTotal+
            "\nTax:\t\t " +this.tax+
            "\nTotal:\t\t " +"Php"+this.totalCost+
            "\n==============================================\t " +
            "\nDate: " +date.format(dateNtime.getTime())+
            "\t\tTime: " +time.format(dateNtime.getTime())+
            "\n\n\t\tThant you\n");
    }
        else
            totalScreen.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    private void price2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price2ActionPerformed

    private void price3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price3ActionPerformed

    private void price4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price4ActionPerformed

    private void price5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price5ActionPerformed

    private void price6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price6ActionPerformed

    private void price7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price7ActionPerformed

    private void price8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price8ActionPerformed

    private void price9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price9ActionPerformed

    private void price1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price1ActionPerformed

    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField30ActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
     totalScreen.setText("");
     firstNameTxt.setText("");
     lastNameTxt.setText("");
     product1.setSelected(false);
     product2.setSelected(false);
     product3.setSelected(false);
     product4.setSelected(false);
     product5.setSelected(false);
     product6.setSelected(false);
     product7.setSelected(false);
     product8.setSelected(false);
     product9.setSelected(false);
     product10.setSelected(false);
     p1.setText("0");
     p2.setText("0");
     p3.setText("0");
     p4.setText("0");
     p5.setText("0");
     p6.setText("0");
     p7.setText("0");
     p8.setText("0");
     p9.setText("0");
     p10.setText("0");
     p1.setEnabled(false);
     p2.setEnabled(false);
     p3.setEnabled(false);
     p4.setEnabled(false);
     p5.setEnabled(false);
     p6.setEnabled(false);
     p7.setEnabled(false);
     p8.setEnabled(false);
     p9.setEnabled(false);
     p10.setEnabled(false);
     for(int i = 0; i<this.productPurchased.size(); i++){
         productPurchased.remove(i);
     }
     jTextArea1.setText("");
     
    }//GEN-LAST:event_resetBtnActionPerformed

    private void firstNameTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstNameTxtMouseClicked
         Double reference = new Double(932785 + Math.random()*5678);
         Integer ref = reference.intValue();
         String costumerRef = ref.toString();
         costumerRefTxt.setText(costumerRef);
    }//GEN-LAST:event_firstNameTxtMouseClicked

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
     this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
    String isText = jTextArea1.getText();
        if(!isText.equals("")){
        try{
            jTextArea1.print();
        }catch(Exception e){
            System.out.println(e);
        }
        }else{
            System.out.println("no text");
        }
    }//GEN-LAST:event_printBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField costumerRefTxt;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p10;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField p4;
    private javax.swing.JTextField p5;
    private javax.swing.JTextField p6;
    private javax.swing.JTextField p7;
    private javax.swing.JTextField p8;
    private javax.swing.JTextField p9;
    private javax.swing.JTextField price1;
    private javax.swing.JTextField price10;
    private javax.swing.JTextField price2;
    private javax.swing.JTextField price3;
    private javax.swing.JTextField price4;
    private javax.swing.JTextField price5;
    private javax.swing.JTextField price6;
    private javax.swing.JTextField price7;
    private javax.swing.JTextField price8;
    private javax.swing.JTextField price9;
    private javax.swing.JButton printBtn;
    private javax.swing.JCheckBox product1;
    private javax.swing.JCheckBox product10;
    private javax.swing.JCheckBox product2;
    private javax.swing.JCheckBox product3;
    private javax.swing.JCheckBox product4;
    private javax.swing.JCheckBox product5;
    private javax.swing.JCheckBox product6;
    private javax.swing.JCheckBox product7;
    private javax.swing.JCheckBox product8;
    private javax.swing.JCheckBox product9;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel totalScreen;
    // End of variables declaration//GEN-END:variables
}
